// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYY7OOi55iDETQKpcecILihD9Q0hXCFFM',
    appId: '1:689973307689:web:e678f5684be339a44c6f38',
    messagingSenderId: '689973307689',
    projectId: 'frnd-version',
    authDomain: 'frnd-version.firebaseapp.com',
    storageBucket: 'frnd-version.firebasestorage.app',
    measurementId: 'G-HT6B2TB74H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuoQ1ng6jSxJyE8dix2QAQLuQRGxQDbG0',
    appId: '1:689973307689:android:cff99eadaf68bf294c6f38',
    messagingSenderId: '689973307689',
    projectId: 'frnd-version',
    storageBucket: 'frnd-version.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFZVDebwxG0kZu9ag8DiFgf_sssgj74H8',
    appId: '1:689973307689:ios:195d58c1cb5b53134c6f38',
    messagingSenderId: '689973307689',
    projectId: 'frnd-version',
    storageBucket: 'frnd-version.firebasestorage.app',
    iosBundleId: 'com.example.frnds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFZVDebwxG0kZu9ag8DiFgf_sssgj74H8',
    appId: '1:689973307689:ios:195d58c1cb5b53134c6f38',
    messagingSenderId: '689973307689',
    projectId: 'frnd-version',
    storageBucket: 'frnd-version.firebasestorage.app',
    iosBundleId: 'com.example.frnds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYY7OOi55iDETQKpcecILihD9Q0hXCFFM',
    appId: '1:689973307689:web:d755ef2ee93d3df34c6f38',
    messagingSenderId: '689973307689',
    projectId: 'frnd-version',
    authDomain: 'frnd-version.firebaseapp.com',
    storageBucket: 'frnd-version.firebasestorage.app',
    measurementId: 'G-EHM0MEH79V',
  );
}
